# Compete 
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]] 
repo = 'Shougo/neco-vim' 
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

# language plugin
## Vim Plugin for Ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

## D language Plugin
[[plugins]]
repo = 'JesseKPhillips/d.vim'
on_ft = ['d']

## Crystal Plugin
[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = ['crystal']

