[[plugins]]
repo = 'Shougo/dein.vim'

# Compete 
[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] 
repo = 'Shougo/neco-vim' 

[[plugins]]
repo = 'Shougo/neco-syntax'


# User Inter Face #
## Statusline extension Plugin
[[plugins]]
repo = 'itchyny/lightline.vim'

## A tree explorer
[[plugins]]
repo = 'scrooloose/nerdtree'

# Utility #
## Vim Web API Plugins
[[plugins]]
repo = 'mattn/webapi-vim'

## Open URI with browser
[[plugins]]
repo = 'tyru/open-browser.vim'

# Command and General Text #
## Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

## Git Viewer
[[plugins]] 
repo = 'cohama/agit.vim'

## Editor Config
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

## Gist Plugin
[[plugins]]
repo = 'mattn/gist-vim'

## Unite Interface
[[plugins]]
repo = 'Shougo/unite.vim'

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'

