
# language plugin
## Vim Plugin for Ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

## D language Plugin
[[plugins]]
repo = 'JesseKPhillips/d.vim'
on_ft = ['d']

## Crystal Plugin
[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = ['crystal']

## LaTeX Plugin
[[plugin]]
repo = 'lervag/vimtex'
on_ft = ['tex']

## Go Plugin
[[plugin]]
repo = 'fatih/vim-go'
on_ft = ['go']
