[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

# Compete
[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]] 
repo = 'Shougo/neco-vim' 

[[plugins]]
repo = 'Shougo/neco-syntax'


# User Inter Face #
## Statusline extension Plugin
[[plugins]]
repo = 'itchyny/lightline.vim'

# Utility #
## Vim Web API Plugins
[[plugins]]
repo = 'mattn/webapi-vim'

## Open URI with browser
[[plugins]]
repo = 'tyru/open-browser.vim'

# Command and General Text #
## Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

## Git Viewer
[[plugins]] 
repo = 'cohama/agit.vim'


## Gist Plugin
[[plugins]]
repo = 'mattn/gist-vim'

## Unite Interface
[[plugins]]
repo = 'Shougo/denite.nvim'

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-syntastic/syntastic'
# vimfiler
[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'fuenor/vim-wordcount'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'hisaknown/nanomap.vim'

[[plugins]]
repo = 'tyrannicaltoucan/vim-quantum'
hook_add = '''
  set termguicolors
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme quantum
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
