# language plugin
## Vim Plugin for Ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']


## Crystal Plugin
[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = ['crystal']

## LaTeX Plugin
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

## Go Plugin
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['cpp']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c','cpp']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo ='violetyk/iikanji-markdown.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'rhysd/vim-wasm'
on_ft = ['wasm','wat']

[[plugins]]
repo = 'moro/vim-review'
on_ft = ['review']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'scalameta/coc-metals'
